### ISSUE TITLE
Update website with the results from the new scRNA-seq datasets

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/rare_disease_celltyping#57] opened 2023-12-19 15:46 UTC
How do we deal with having two scRNA-seq datasets?

**Comment by bschilder** [comment] 2023-12-21 20:42
Duplicate of this issue:
- https://github.com/neurogenomics/rare_disease_celltyping_apps/issues/6

The short answer is, we change the app to allow users to select one or the other.

**Closed by bschilder** 2023-12-21 20:42 UTC
